const ACTIONS = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  GET_SEARCH_TEXT: "GET_SEARCH_TEXT",
  ADD_SEARCH_TEXT: "ADD_SEARCH_TEXT",
  REMOVE_SEARCH_TEXT: "REMOVE_SEARCH_TEXT",
  ADD_SEARCH_PRODUCT: "ADD_SEARCH_PRODUCT",
  REMOVE_SEARCH_PRODUCT: "REMOVE_SEARCH_PRODUCT",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  SAVE_CHECKOUT_DATA: "SAVE_CHECKOUT_DATA",
  REMOVE_CHECKOUT_DATA: "REMOVE_CHECKOUT_DATA",
  ADD_FAVORITE: "ADD_FAVORITE",
  REMOVE_FAVORITE: "REMOVE_FAVORITE"
};

export default ACTIONS;
